# Generated by Django 4.2.30 on 2026-04-25 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActInput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('act_type', models.CharField(choices=[('ks2', 'Акт КС-2 (приёмка работ)'), ('ks3', 'Справка КС-3 (стоимость работ)')], max_length=3, verbose_name='Тип акта')),
                ('document_number', models.CharField(max_length=50, verbose_name='Номер документа')),
                ('contract_number', models.CharField(max_length=50, verbose_name='Номер договора')),
                ('contract_date', models.DateField(verbose_name='Дата договора')),
                ('report_from', models.DateField(verbose_name='Отчётный период с')),
                ('report_to', models.DateField(verbose_name='Отчётный период по')),
                ('investor', models.CharField(max_length=200, verbose_name='Инвестор (наименование)')),
                ('investor_okpo', models.CharField(blank=True, max_length=20, verbose_name='ОКПО инвестора')),
                ('customer', models.CharField(max_length=200, verbose_name='Заказчик/Генподрядчик')),
                ('customer_okpo', models.CharField(blank=True, max_length=20, verbose_name='ОКПО заказчика')),
                ('contractor', models.CharField(default='ООО "МОСТООТРЯД-69"', editable=False, max_length=200, verbose_name='Подрядчик')),
                ('contractor_okpo', models.CharField(default='34810147', editable=False, max_length=20, verbose_name='ОКПО подрядчика')),
                ('construction', models.CharField(max_length=200, verbose_name='Стройка (наименование, адрес)')),
                ('object_name', models.CharField(blank=True, max_length=200, verbose_name='Объект (для КС-2)')),
                ('operation', models.CharField(default='Выполнение строительно-монтажных работ', max_length=200, verbose_name='Вид операции (для КС-3)')),
                ('okdp', models.CharField(default='4530', editable=False, max_length=10, verbose_name='Вид деятельности по ОКДП')),
                ('surrender_position', models.CharField(max_length=100, verbose_name='Должность сдавшего')),
                ('surrender_signature', models.CharField(max_length=100, verbose_name='Подпись сдавшего (ФИО)')),
                ('accept_position', models.CharField(max_length=100, verbose_name='Должность принявшего')),
                ('accept_signature', models.CharField(max_length=100, verbose_name='Подпись принявшего (ФИО)')),
                ('vat_rate', models.CharField(default='20%', max_length=10, verbose_name='Ставка НДС')),
                ('smeta', models.CharField(blank=True, max_length=50, verbose_name='Сметная стоимость (для КС-2)')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлен'), ('approved', 'Согласован'), ('rejected', 'Отклонён')], default='draft', max_length=10, verbose_name='Статус')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал пользователь')),
            ],
            options={
                'verbose_name': 'Ввод данных акта',
                'verbose_name_plural': 'Ввод данных актов',
                'db_table': 'acts_input',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=20, verbose_name='Позиция по смете')),
                ('name', models.TextField(verbose_name='Наименование работ/затрат')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Код (для КС-3)')),
                ('number_pricelist', models.CharField(blank=True, max_length=50, verbose_name='№ расценки (для КС-2)')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='Ед. измерения')),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Количество')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Цена за единицу, руб.')),
                ('cost_from_start', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Стоимость с начала проведения работ, руб.')),
                ('cost_from_year', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Стоимость с начала года, руб.')),
                ('cost_report_period', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Стоимость за отчётный период, руб.')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядковый номер')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='acts.actinput', verbose_name='Акт')),
            ],
            options={
                'verbose_name': 'Вид работ',
                'verbose_name_plural': 'Виды работ',
                'db_table': 'acts_work_items',
                'ordering': ['order', 'id'],
            },
        ),
    ]
