# Generated by Django 4.2.30 on 2026-05-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actinput',
            name='customer_okpo',
            field=models.CharField(max_length=20, verbose_name='ОКПО заказчика'),
        ),
        migrations.AlterField(
            model_name='actinput',
            name='investor_okpo',
            field=models.CharField(max_length=20, verbose_name='ОКПО инвестора'),
        ),
        migrations.AlterField(
            model_name='actinput',
            name='operation',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Вид операции (для КС-3)'),
        ),
        migrations.AlterField(
            model_name='actinput',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('check', 'На проверке'), ('approved', 'Утверждён'), ('rejected', 'Отклонён')], default='draft', max_length=20, verbose_name='Статус'),
        ),
    ]
