# Generated by Django 4.2.30 on 2026-05-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0002_alter_actinput_customer_okpo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actinput',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлен'), ('approved', 'Согласован'), ('rejected', 'Отклонён')], default='draft', max_length=10, verbose_name='Статус'),
        ),
    ]
