# Generated by Django 4.2.13 on 2026-05-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0003_alter_actinput_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actinput',
            name='contractor',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Подрядчик'),
        ),
        migrations.AlterField(
            model_name='actinput',
            name='contractor_okpo',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='ОКПО подрядчика'),
        ),
        migrations.AlterField(
            model_name='actinput',
            name='investor',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Инвестор (наименование)'),
        ),
        migrations.AlterField(
            model_name='actinput',
            name='investor_okpo',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='ОКПО инвестора'),
        ),
        migrations.AlterField(
            model_name='actinput',
            name='okdp',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Вид деятельности по ОКДП'),
        ),
    ]
